stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: "docker.io/${REGISTRY_USER}/app2"
  STORAGE_DRIVER: "vfs"
  BUILDAH_ISOLATION: "chroot"
  BUILDAH_FORMAT: "docker"
  # Tag will be fetch automatically once create, even for a simple update(first thing to do once everything ok)
  IMAGE_TAG: $CI_COMMIT_TAG

# Environment and File Checking
test_stage:
  stage: test
  image: python:3.13-slim
  script:
    - pip install --no-cache-dir --upgrade pip
    - pip install --no-cache-dir streamlit pillow pandas mysql-connector-python
    - python -m py_compile ./Hotel-Management-using-SQL-main/app/Main_Page.py
    

# Steps required to create and push image to private registry
build_stage:
  stage: build 
  needs: ["test_stage"]
  # fixed image for more control during the whole process
  image: quay.io/buildah/stable:v1.43.1-immutable
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
      when: on_success
  
  before_script:
      # Connexion to private docker registry
    - buildah login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN_HUB}" docker.io
  script:
      # Create an image
    - buildah bud -t "${IMAGE_NAME}:${IMAGE_TAG}" .
      # Pushing image to the private registry
    - buildah push "${IMAGE_NAME}:${IMAGE_TAG}"
      # list images 
  after_script:
    - buildah images

# Steps required to pull image from private repository and deploy app on workers nodes with ansible
deploy_stage:
  stage: deploy


## Work in progress