services:
  
  # APPLICATION
  app_web:

    image: ###### image chargé depuis le registry 
    container_name: app_docker-compose
    restart: unless-stopped
    ports:
      - "8501:8501"
    networks:
      - back
    env_file:
      - .env.app
    depends_on:
      mysql:
        condition: service_healthy
  

  # BDD

  mysql:
    image: mysql:8.4
    networks:
      - back
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./db/commands.sql:/docker-entrypoint-initdb.d/commands.sql:ro
      - bdd_data:/var/lib/mysql
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin", "ping", "-h", "localhost", "-u", "$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

    
  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: phpmyadmin
    ports:
      - "8080:80"
    networks:
      - back
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=3306

volumes:
  bdd_data:
    driver: local


networks:
  back:
    driver: bridge
    #driver_opts:
      #com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  