---
# tasks file for deploy_app

- name: update cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"
  tags: always

## Log into a Docker registry
- name: Connexion to private registry
  community.docker.docker_login:
    registry_url: https://index.docker.io/v1/
    username: "{{ lookup('ansible.builtin.env', 'REGISTRY_USER') }}"
    password: "{{ lookup('ansible.builtin.env', 'REGISTRY_TOKEN_HUB') }}"
  no_log: true

- name: app folder directory create
  ansible.builtin.file:
    path: /opt/streamlit_app
    state: directory
    owner: "{{user_owner}}"
    group: "{{user_group}}"
    mode: '0755'

- name: Generate docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/streamlit_app/docker-compose.yml
    owner: "{{user_owner}}"
    group: "{{user_group}}"

- name: set up templates .env.app
  ansible.builtin.template:
    src: env.app.j2
    dest: /opt/streamlit_app/.env.app  ## still in progress
    owner: "{{user_owner}}"
    group: "{{user_group}}"
    mode: '0600'


- name: set up templates .env.db
  ansible.builtin.template:
    src: env.db.j2
    dest: /opt/streamlit_app/.env.db  ## still in progress
    owner: "{{user_owner}}"
    group: "{{user_group}}"
    mode: '0600'


  
