all:    

  children:

    workers:

      hosts:

        worker1:

          ansible_host: worker1
        
        worker2:

          ansible_host: worker2
    
    servers:

      hosts:

        server1:

          ansible_host: 192.168.9.109
          ansible_user: awx

        server2:

          ansible_host: 192.168.9.110
          ansible_user: gitea

        server3: 

          ansible_host: 192.168.9.120
          ansible_user: marc
    
    local:

      hosts:

        localhost:

          ansible_connection: local
          